export const PERMISSIONS = {
  // Administration
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_BRANCHES: 'VIEW_BRANCHES',
  CREATE_BRANCH: 'CREATE_BRANCH',
  EDIT_BRANCH: 'EDIT_BRANCH',
  DELETE_BRANCH: 'DELETE_BRANCH',
  
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  DELETE_USER: 'DELETE_USER',
  
  VIEW_ROLES: 'VIEW_ROLES',
  CREATE_ROLE: 'CREATE_ROLE',
  EDIT_ROLE: 'EDIT_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  
  MANAGE_SYSTEM_SETTINGS: 'MANAGE_SYSTEM_SETTINGS',

  // Master Data
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  EDIT_PRODUCT: 'EDIT_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  
  VIEW_CATEGORIES: 'VIEW_CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  
  VIEW_RECIPES: 'VIEW_RECIPES',
  CREATE_RECIPE: 'CREATE_RECIPE',
  EDIT_RECIPE: 'EDIT_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  
  VIEW_SUPPLIERS: 'VIEW_SUPPLIERS',
  CREATE_SUPPLIER: 'CREATE_SUPPLIER',
  EDIT_SUPPLIER: 'EDIT_SUPPLIER',
  DELETE_SUPPLIER: 'DELETE_SUPPLIER',

  // Inventory & Stock
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  UPDATE_INVENTORY: 'UPDATE_INVENTORY',
  
  VIEW_PO: 'VIEW_PO',
  CREATE_PO: 'CREATE_PO',
  APPROVE_PO: 'APPROVE_PO',
  
  VIEW_GRN: 'VIEW_GRN',
  CREATE_GRN: 'CREATE_GRN',
  
  VIEW_WASTAGE: 'VIEW_WASTAGE',
  CREATE_WASTAGE: 'CREATE_WASTAGE',
  
  VIEW_STOCK_TRANSFERS: 'VIEW_STOCK_TRANSFERS',
  CREATE_STOCK_TRANSFER: 'CREATE_STOCK_TRANSFER',
  APPROVE_STOCK_TRANSFER: 'APPROVE_STOCK_TRANSFER',

  // Operations & Sales
  ACCESS_POS: 'ACCESS_POS',
  PROCESS_SALES: 'PROCESS_SALES',
  APPLY_DISCOUNT: 'APPLY_DISCOUNT',
  PROCESS_RETURNS: 'PROCESS_RETURNS',
  VOID_SALE: 'VOID_SALE',
  PROCESS_REFUND: 'PROCESS_REFUND',
  VIEW_SHIFT_SUMMARY: 'VIEW_SHIFT_SUMMARY',
  MANAGE_CASH_DRAWER: 'MANAGE_CASH_DRAWER',
  
  VIEW_SALES_HISTORY: 'VIEW_SALES_HISTORY',
  
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  EDIT_CUSTOMER: 'EDIT_CUSTOMER',
  
  VIEW_EXPENSES: 'VIEW_EXPENSES',
  CREATE_EXPENSE: 'CREATE_EXPENSE',

  // Reporting
  VIEW_ALL_REPORTS: 'VIEW_ALL_REPORTS',
  VIEW_BRANCH_REPORTS: 'VIEW_BRANCH_REPORTS',
} as const;

export type Permission = keyof typeof PERMISSIONS;

export const PERMISSION_GROUPS = [
  {
    group: "Administration",
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.VIEW_BRANCHES, PERMISSIONS.CREATE_BRANCH, PERMISSIONS.EDIT_BRANCH, PERMISSIONS.DELETE_BRANCH,
      PERMISSIONS.VIEW_USERS, PERMISSIONS.CREATE_USER, PERMISSIONS.EDIT_USER, PERMISSIONS.DELETE_USER,
      PERMISSIONS.VIEW_ROLES, PERMISSIONS.CREATE_ROLE, PERMISSIONS.EDIT_ROLE, PERMISSIONS.DELETE_ROLE,
      PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
    ]
  },
  {
    group: "Master Data",
    permissions: [
      PERMISSIONS.VIEW_PRODUCTS, PERMISSIONS.CREATE_PRODUCT, PERMISSIONS.EDIT_PRODUCT, PERMISSIONS.DELETE_PRODUCT,
      PERMISSIONS.VIEW_CATEGORIES, PERMISSIONS.CREATE_CATEGORY, PERMISSIONS.EDIT_CATEGORY, PERMISSIONS.DELETE_CATEGORY,
      PERMISSIONS.VIEW_RECIPES, PERMISSIONS.CREATE_RECIPE, PERMISSIONS.EDIT_RECIPE, PERMISSIONS.DELETE_RECIPE,
      PERMISSIONS.VIEW_SUPPLIERS, PERMISSIONS.CREATE_SUPPLIER, PERMISSIONS.EDIT_SUPPLIER, PERMISSIONS.DELETE_SUPPLIER,
    ]
  },
  {
    group: "Inventory & Stock",
    permissions: [
      PERMISSIONS.VIEW_INVENTORY, PERMISSIONS.UPDATE_INVENTORY,
      PERMISSIONS.VIEW_PO, PERMISSIONS.CREATE_PO, PERMISSIONS.APPROVE_PO,
      PERMISSIONS.VIEW_GRN, PERMISSIONS.CREATE_GRN,
      PERMISSIONS.VIEW_WASTAGE, PERMISSIONS.CREATE_WASTAGE,
      PERMISSIONS.VIEW_STOCK_TRANSFERS, PERMISSIONS.CREATE_STOCK_TRANSFER, PERMISSIONS.APPROVE_STOCK_TRANSFER,
    ]
  },
  {
    group: "Operations & Sales",
    permissions: [
      PERMISSIONS.ACCESS_POS, PERMISSIONS.PROCESS_SALES, PERMISSIONS.APPLY_DISCOUNT, PERMISSIONS.PROCESS_RETURNS,
      PERMISSIONS.VOID_SALE, PERMISSIONS.PROCESS_REFUND, PERMISSIONS.VIEW_SHIFT_SUMMARY, PERMISSIONS.MANAGE_CASH_DRAWER,
      PERMISSIONS.VIEW_SALES_HISTORY,
      PERMISSIONS.VIEW_CUSTOMERS, PERMISSIONS.CREATE_CUSTOMER, PERMISSIONS.EDIT_CUSTOMER,
      PERMISSIONS.VIEW_EXPENSES, PERMISSIONS.CREATE_EXPENSE,
    ]
  },
  {
    group: "Reporting",
    permissions: [
      PERMISSIONS.VIEW_ALL_REPORTS,
      PERMISSIONS.VIEW_BRANCH_REPORTS,
    ]
  }
];
