export const PERMISSIONS = {
  // Master Data & Admin
  MANAGE_BRANCHES: 'MANAGE_BRANCHES',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_SYSTEM_SETTINGS: 'MANAGE_SYSTEM_SETTINGS',
  
  // Products & Inventory
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
  MANAGE_CATEGORIES: 'MANAGE_CATEGORIES',
  MANAGE_RECIPES: 'MANAGE_RECIPES',
  MANAGE_SUPPLIERS: 'MANAGE_SUPPLIERS',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  MANAGE_PO: 'MANAGE_PO', // Purchase Orders
  MANAGE_GRN: 'MANAGE_GRN', // Goods Receiving Notes
  MANAGE_WASTAGE: 'MANAGE_WASTAGE',
  APPROVE_STOCK_TRANSFERS: 'APPROVE_STOCK_TRANSFERS',
  STOCK_TRANSFERS: 'STOCK_TRANSFERS',

  // Sales & Operations
  VIEW_ASSIGNED_BRANCH: 'VIEW_ASSIGNED_BRANCH',
  MANAGE_EXPENSES: 'MANAGE_EXPENSES',
  POS_SALES: 'POS_SALES',
  CUSTOMER_MANAGEMENT: 'CUSTOMER_MANAGEMENT',
  RECEIPT_PRINTING: 'RECEIPT_PRINTING',

  // Reporting
  VIEW_ALL_REPORTS: 'VIEW_ALL_REPORTS',
  VIEW_BRANCH_REPORTS: 'VIEW_BRANCH_REPORTS',
} as const;

export type Permission = keyof typeof PERMISSIONS;

export const PERMISSION_GROUPS = [
  {
    group: "Administration",
    permissions: [
      PERMISSIONS.MANAGE_BRANCHES,
      PERMISSIONS.MANAGE_USERS,
      PERMISSIONS.MANAGE_ROLES,
      PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
    ]
  },
  {
    group: "Master Data",
    permissions: [
      PERMISSIONS.MANAGE_PRODUCTS,
      PERMISSIONS.MANAGE_CATEGORIES,
      PERMISSIONS.MANAGE_RECIPES,
      PERMISSIONS.MANAGE_SUPPLIERS,
    ]
  },
  {
    group: "Inventory & Stock",
    permissions: [
      PERMISSIONS.MANAGE_INVENTORY,
      PERMISSIONS.MANAGE_PO,
      PERMISSIONS.MANAGE_GRN,
      PERMISSIONS.MANAGE_WASTAGE,
      PERMISSIONS.APPROVE_STOCK_TRANSFERS,
      PERMISSIONS.STOCK_TRANSFERS,
    ]
  },
  {
    group: "Operations & Sales",
    permissions: [
      PERMISSIONS.VIEW_ASSIGNED_BRANCH,
      PERMISSIONS.MANAGE_EXPENSES,
      PERMISSIONS.POS_SALES,
      PERMISSIONS.CUSTOMER_MANAGEMENT,
      PERMISSIONS.RECEIPT_PRINTING,
    ]
  },
  {
    group: "Reporting",
    permissions: [
      PERMISSIONS.VIEW_ALL_REPORTS,
      PERMISSIONS.VIEW_BRANCH_REPORTS,
    ]
  }
];
